version: "3.8"

services:
  db:
    image: postgres:9.3
    restart: always
    container_name: postgresql_metabase
    environment:
      - POSTGRES_USER=child
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=metabase2
      - POSTGRES_DB=child
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  metabase2:
    image: metabase/metabase
    ports:
      - 3000:3000
    container_name: metabase2
    #restart: "always"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase2
      - MB_DB_PORT=5432
      - MB_DB_USER=child
      - MB_DB_PASS=db
      - MB_DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./app/metabase2:/metabase-data